import { NextResponse, type NextRequest } from "next/server";

import { getSessionProfile } from "@/lib/auth/guards";
import { QUICK_BATCH_SIZE } from "@/lib/batches";
import { fileSlug, isSameOrigin } from "@/lib/http";
import { batchCsv, csvDownload, fetchBatchCodes } from "@/lib/qr-export";
import { createClient } from "@/lib/supabase/server";
import { uuidSchema } from "@/lib/validation";

const dayStamp = new Intl.DateTimeFormat("fr-CA", { timeZone: "Africa/Tunis" }); // YYYY-MM-DD

/**
 * One-click print run: creates 100 single-use QR codes for the merchant
 * (unscanned, random UUIDs generated by Postgres) and answers with the CSV as
 * an attachment, so the admin's browser downloads it immediately. Failures
 * redirect back to the merchant page with a visible error (the button is a
 * plain HTML form post, so a JSON error body would replace the page).
 */
export async function POST(request: NextRequest, ctx: RouteContext<"/admin/merchants/[id]/qr-batch">) {
  if (!isSameOrigin(request)) {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }

  const session = await getSessionProfile();
  if (!session || session.profile.role !== "super_admin") {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }

  const { id } = await ctx.params;
  if (!uuidSchema.safeParse(id).success) {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }

  const supabase = await createClient();
  const { data: merchant } = await supabase.from("merchants").select("id, name").eq("id", id).maybeSingle();
  if (!merchant) return NextResponse.json({ error: "not_found" }, { status: 404 });

  const today = dayStamp.format(new Date());
  const { data: batchId, error } = await supabase.rpc("generate_qr_batch", {
    p_merchant_id: merchant.id,
    p_quantity: QUICK_BATCH_SIZE,
    p_label: `Lot du ${today}`,
  });
  if (error || !batchId) {
    console.error("[admin] quick batch generation failed:", error?.message);
    return backToMerchant(request, merchant.id, "error");
  }

  try {
    const rows = await fetchBatchCodes(supabase, batchId);
    return csvDownload(batchCsv(rows), `hyperfid-${fileSlug(merchant.name, "commerce")}-${today}.csv`);
  } catch (exportError) {
    // The codes exist; the batch table on the merchant page offers the CSV again.
    console.error("[admin] quick batch export failed:", exportError);
    return backToMerchant(request, merchant.id, "export_error");
  }
}

function backToMerchant(request: NextRequest, merchantId: string, status: "error" | "export_error") {
  const url = new URL(`/admin/merchants/${merchantId}`, request.url);
  url.searchParams.set("batch", status);
  return NextResponse.redirect(url, 303);
}
